# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# CI Build Pipeline with Unit Test Result & Coverage Report


jobs:
- job: 'Test'
  pool:
    vmImage: 'vs2017-win2016' # other options: 'macOS-10.14', 'vs2017-win2016'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      pip install pytest pytest-azurepipelines
      pip install pytest-cov
      #pytest --doctest-modules --junitxml=junit/test-results.xml --cov=./src/ --cov-config=./src/.coveragerc --cov-report=html
      python run.py
    displayName: 'pytest'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python 3.7'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'